name: AWVS14_Update
  
on:
  repository_dispatch:
    types: [Awvs_Update_Action]
  workflow_dispatch:

jobs:
  AWVS14_Update:
    name: AWVS14_Update
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Data 
        id: getDingData
        run: |
          # 获取用户设置的仓库URL，如果没有，则使用github仓库链接
          REPOSITORY="${{GITHUB.REPOSITORY}}"
          echo "::set-output name=REPOSITORY::${REPOSITORY#*/}"

          RESPONSE="$(curl -sLm 10 https://api.github.com/repos/${{ GITHUB.REPOSITORY }})"
          DESCRIPTION="$(jq -r .description <(echo ${RESPONSE}))"
          echo "::set-output name=DESCRIPTION::${DESCRIPTION}"

          URL="$(jq -r .homepage <(echo ${RESPONSE}))"
          if [ -n "${URL}" ]; then
            echo "::set-output name=URL::${URL}"
          else
            echo "::set-output name=URL::${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}"
          fi
      - 
        name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ SECRETS.DING_TOKEN }}
          secret: ${{ SECRETS.DING_SECRET }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "${{ steps.getDingData.outputs.REPOSITORY }} WorkFlow Run ${{ GITHUB.JOB }} Success!",
                  "title":  "${{ steps.getDingData.outputs.DESCRIPTION }}",
                  "picUrl": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                  "messageUrl": "${{ steps.getDingData.outputs.URL }}"
              }
            }