name: AWVS14_Update
  
on:
  repository_dispatch:
    types: [Awvs_Update_Action]
  workflow_dispatch:

jobs:
  AWVS14_Update:
    name: AWVS14_Update
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Url # 获取用户设置的仓库URL，如果没有，则使用github仓库链接
        id: getUrl
        run: |
          url="$(curl -sLm 10 https://api.github.com/repos/${{ github.repository }} | jq .homepage | tr -d '"')"
          if [ -n "${url}" ]; then
            echo "::set-output name=url::${url}"
          else
            echo "::set-output name=url::${{ github.server_url }}/${{ github.repository }}"
          fi
          set -ex
          echo "${{ GITHUB.JOB }}"
          echo "${{ github.job }}"
          echo "${{ github.* }}"
      # - 
      #   name: Send dingding notify
      #   uses: zcong1993/actions-ding@master
      #   with:
      #     dingToken: ${{ secrets.DING_TOKEN }}
      #     secret: ${{ secrets.DING_SECRET }}
      #     body: |
      #       {
      #         "msgtype": "link",
      #         "link": {
      #             "text": "${{ github.repository }} Update Success!",
      #             "title": "${{ github.repository }} Update Success!",
      #             "picUrl": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
      #             "messageUrl": "${{ steps.getUrl.outputs.url }}"
      #         }
      #       }